FROM node:20 as builder

WORKDIR /app
COPY VeilleTechnoFront/package.json ./
ENV ESBUILD_DISABLE_SERVICE=true
RUN npm cache clean --force
RUN npm install --legacy-peer-deps
COPY VeilleTechnoFront/ ./
RUN npm run build
FROM nginx:alpine
RUN rm /etc/nginx/conf.d/default.conf

COPY Docker/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]