FROM maven:3.9.9
WORKDIR /app
COPY VeilleTechnoBack /app
EXPOSE 8080
CMD ["mvn", "spring-boot:run", "-Dspring-boot.run.profiles=docker", "-Dspring-boot.run.jvmArguments=-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0 -XX:+UseG1GC"]