FROM node:20 AS builder
WORKDIR /app
COPY VeilleTechnoFront/package.json ./

RUN rm -rf node_modules package-lock.json yarn.lock || true
RUN npm install
RUN npm install rollup
RUN npm install @rollup/rollup-linux-x64-gnu
RUN npm install web-vitals
FROM node:20
WORKDIR /app

COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app .

EXPOSE 5173

CMD ["npm","run","dev"]
